---
  # - name: Update Apt Cache
  #   shell: apt-get update

  # - name: Install Softwares
  #   apt: name={{item}} state=present
  #   with_items:
  #     - git
  #     - tmux
  #
  - name: Get my config
    git: repo=https://github.com/owenyang0/config.git
         dest=~/config
         version=ubuntu
    sudo: no

  - name: Config my vim vundle
    git: repo=https://github.com/gmarik/Vundle.vim.git
         dest=~/.vim/bundle/Vundle.vim
    sudo: no
    
  - name: Replace the config file
    copy: src=config/.ssh/ dest=~/.ssh/ owner=vagrant group=vagrant directory_mode=true mode=600
    sudo: no

# - name: Apply my config
#   shell: bash ~/config/autolink
